spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      spring:
        security:
          user:
            password: 123
            name: user

